### ISSUE TITLE
For chatwoot outgoing bot URL the documentation should read `/chatwoot/webhook`

### ISSUE THREAD

**Issue by mattcam** [douglara/chatwoot-botpress-bridge#13]
Issue: when making request to bridge 404 occuring.

Resolution: chage `/chatroot/webhook` to `/chatwoot/webhook`

The source of the confusion about url is here
![Screenshot 2023-06-30 at 6 06 26 pm](https://github.com/douglara/chatwoot-botpress-bridge/assets/3451548/dcab37b8-1a11-48b5-81a4-04a8021a4efe)

Also refer to comment here https://github.com/douglara/chatwoot-botpress-bridge/issues/12#issuecomment-1607629084 which helped me with resolving this issue.

@douglara thank you so much for this bridge.

**Comment by douglara** [comment]
Hello @mattcam this problem is because google translate :grimacing:
But it would be nice to create a documentation of this in English

Thanks friend!
