### ISSUE TITLE
Problema ao criar BOT

### ISSUE THREAD

**Issue by TIUNIFAP** [douglara/chatwoot-botpress-bridge#14]
![image](https://github.com/douglara/chatwoot-botpress-bridge/assets/63851508/0cd8dfeb-310a-4fad-99c6-324b79fb87a3)
Ola estou criando a conexao do botpress com o chatwoot e esta apresentando esse erro

**Comment by douglara** [comment]
Olá!
Isso parece ser um problema com o seu Chatwoot, diz que não encontrou o banco de dados chatwoot_dev.
Segue um manual de como testar:
https://www.linkedin.com/pulse/subindo-um-ambiente-de-desenvolvimento-chatbot-poderoso-douglas-lara/
