### ISSUE TITLE
Unable to deploy on CapRover

### ISSUE THREAD

**Issue by WEBudoGT** [douglara/chatwoot-botpress-bridge#6]
I'm trying to deploy using caprover but I'm getting this error:

Deploy failed!
Error: (HTTP code 404) unexpected - manifest for douglara/chatwoot-botpress-bridge:latest not found: manifest unknown: manifest unknown

**Comment by WEBudoGT** [comment]
I was able to deploy putting the files on a tar file and using the tar method on CapRover

**Comment by douglara** [comment]
Sorry I need to fix docker hub added `latest` tag, for now I updated the README
